package com.atguigu.wechat.pojo;

import lombok.Data;

/**
 * 后台资源类
 */
@Data
public class Resources {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.rhash
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String rhash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.rkey
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String rkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.rtitle
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String rtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources.rtype
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String rtype;

    public Resources() {
    }

    public Resources(String rhash, String rkey, String rtitle, String rtype) {
        this.rhash = rhash;
        this.rkey = rkey;
        this.rtitle = rtitle;
        this.rtype = rtype;
    }
}