package com.atguigu.wechat.pojo;

import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

public class User {
    public User(String openId, String sessionKey, String createTime, String lastVisitTime, String gender, String nickName, String avatarUrl) {
        this.openId = openId;
        this.sessionKey = sessionKey;
        this.createTime = createTime;
        this.lastVisitTime = lastVisitTime;
        this.gender = gender;
        this.nickName = nickName;
        this.avatarUrl = avatarUrl;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.session_key
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_visit_time
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String lastVisitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_id
     *
     * @return the value of user.open_id
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_id
     *
     * @param openId the value for user.open_id
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.session_key
     *
     * @return the value of user.session_key
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.session_key
     *
     * @param sessionKey the value for user.session_key
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_visit_time
     *
     * @return the value of user.last_visit_time
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getLastVisitTime() {
        return lastVisitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_visit_time
     *
     * @param lastVisitTime the value for user.last_visit_time
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setLastVisitTime(String lastVisitTime) {
        this.lastVisitTime = lastVisitTime == null ? null : lastVisitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbggenerated Mon Apr 25 16:14:34 CST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}