package com.atguigu.wechat.pojo;

import lombok.Data;

/**
 * 用户类
 */
@Data
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.session_key
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_visit_time
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String lastVisitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.manager
     *
     * @mbggenerated Mon May 30 17:39:24 CST 2022
     */
    private String manager;

    public User() {
    }

    public User(String openId, String sessionKey, String createTime, String lastVisitTime, String gender, String nickName, String avatarUrl, String manager) {
        this.openId = openId;
        this.sessionKey = sessionKey;
        this.createTime = createTime;
        this.lastVisitTime = lastVisitTime;
        this.gender = gender;
        this.nickName = nickName;
        this.avatarUrl = avatarUrl;
        this.manager = manager;
    }
}